# Generated by Django 4.2.6 on 2023-12-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likequestion',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_like_question'),
        ),
    ]
