# Generated by Django 4.2.6 on 2023-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_likeanswer_answer_alter_likequestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='positive',
            field=models.BooleanField(),
        ),
    ]
